In [1]:
import requests
import re
import numpy as np

url = 'http://idojarasbudapest.hu/archivalt-idojaras'

honapok = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
hosszok = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
evek = ["2016", "2017"]

#honapok = ['01', '02']
evek = ['2012', '2013', '2014', '2015', '2016', '2017']

data = np.array([]).reshape(-1, 4)


for ev in evek:
    nap = 0
    for i, ho in enumerate(honapok):
        print(ev+' '+ho)
        payload = {'ev':ev, 'ho':ho, 'button':'Mehet'}
        r = requests.get(url, params=payload)

        r = requests.post(url, data=payload)
        r = r.content.decode("utf-8")

        a = re.findall('<td .*?</td>', r)
        a = list(map(lambda a: a.split('>')[1].split('<')[0], a))
        a = np.array(a).reshape(-1, 3)
        print(len(a), 'lett')
        if(len(a) > hosszok[i]): #szokoev levagas
            a = a[0:hosszok[i]] 

        if(len(a) < hosszok[i]): #ha hianyzik duplazas 
            if (hosszok[i]-len(a)) < 3:
                print('POTOLVA',hosszok[i]-len(a))
                a = np.append(a,a[-(hosszok[i]-len(a)):], axis=0)
                
            else:
                print('HIANYOS HONAP')
                  
       
        print(hosszok[i], 'lenne')
        print('\n')
        b = np.arange(nap+1,nap+len(a)+1).reshape(-1,1)
        nap = nap+len(b)
        c = np.append(b, a, axis=1)

        #print(c)
        data = np.append(data, c)



#print(r)
data = data.reshape(-1, 4)

2012 01
31 lett
31 lenne


2012 02
29 lett
28 lenne


2012 03
31 lett
31 lenne


2012 04
30 lett
30 lenne


2012 05
31 lett
31 lenne


2012 06
30 lett
30 lenne


2012 07
31 lett
31 lenne


2012 08
31 lett
31 lenne


2012 09
30 lett
30 lenne


2012 10
31 lett
31 lenne


2012 11
30 lett
30 lenne


2012 12
31 lett
31 lenne


2013 01
31 lett
31 lenne


2013 02
28 lett
28 lenne


2013 03
31 lett
31 lenne


2013 04
30 lett
30 lenne


2013 05
31 lett
31 lenne


2013 06
30 lett
30 lenne


2013 07
30 lett
POTOLVA 1
31 lenne


2013 08
29 lett
POTOLVA 2
31 lenne


2013 09
29 lett
POTOLVA 1
30 lenne


2013 10
31 lett
31 lenne


2013 11
30 lett
30 lenne


2013 12
31 lett
31 lenne


2014 01
31 lett
31 lenne


2014 02
28 lett
28 lenne


2014 03
31 lett
31 lenne


2014 04
30 lett
30 lenne


2014 05
31 lett
31 lenne


2014 06
30 lett
30 lenne


2014 07
31 lett
31 lenne


2014 08
31 lett
31 lenne


2014 09
30 lett
30 lenne


2014 10
31 lett
31 lenne


2014 11
30 lett
30 lenne


2014 12
31 lett
31 lenne


In [2]:
print(data)

len(data)

[['1' '3' '-1' '2.8']
 ['2' '4' '0' '4.4']
 ['3' '6' '1' '3.9']
 ..., 
 ['296' '10.6' '9.3' '7.3']
 ['297' '13.1' '5' '6.8']
 ['298' '12.2' '2.8' '3.6']]


2123

In [3]:
x = data.reshape(-1)
np.savetxt('test.out', data.astype(float), delimiter=',', fmt='%f')

In [4]:
rin = np.loadtxt('test.out', delimiter=',')
print(rin)

[[   1.     3.    -1.     2.8]
 [   2.     4.     0.     4.4]
 [   3.     6.     1.     3.9]
 ..., 
 [ 296.    10.6    9.3    7.3]
 [ 297.    13.1    5.     6.8]
 [ 298.    12.2    2.8    3.6]]
